### PR TITLE
docs(changelog): Add CHANGELOG and SemVer public API description

### PR DESCRIPTION
**Pull request by julienloizelet**
Hi,
In order to create my first release here (1.0.0), I would like to add a CHANGELOG to inform users that we are using the SemVer specification.

I also add a "release" GitHub action that has 2 purposes:

1. Check consistency between the release tag and the source code
2. Force releaser to respect some format for the CHANGELOG file

Please let me know what you think.

Thanks

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Pretty fancy. It's not clear to me whether you're promoting version number *with* `v` or without `v`. My preference and usual habit is "with".

**Comment by julienloizelet** [comment]
>  It's not clear to me whether you're promoting version number _with_ `v` or without `v`. My preference and usual habit is "with".

Well,
my habit is to have tag name _with_ `v` and release name _without_ `v`. I refer to [this SemVer faq](https://semver.org/#is-v123-a-semantic-version).

Do you mind if I use my habit for this repo ?

**Comment by rfay** [comment]
It's fine, and it will absolutely do no harm at this point. However, would you mind using the 'v' for now? All other DDEV and add-on releases do. And in coming months DDEV will pay attention to versions, and allow specifying add-on versions and removing, etc. See https://github.com/ddev/ddev/issues?q=is%3Aissue+is%3Aopen+label%3A%22addon+mechanism%22


The link you quote (thanks) says:

> Is “v1.2.3” a semantic version?
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

It seems to acknowledge the common custom; if you create a release v1.0.0, the release/tag is v1.0.0, the obvious semantic version is 1.0.0

As a result of your concern and your link though, I'll attempt to respect both when thinking about those issues.

**Comment by julienloizelet** [comment]
That's ok for me (there are many debates around this v prefix :) )

I just changed the GitHub action to have both tag and release name with v.

I will merge and create the release after that.

Thanks

**Comment by rfay** [comment]
Thanks for your flexibility. I know how these debates can rage on and on.

**Pull request merged**
